"""duration->time

Revision ID: 23912124a644
Revises: 5fcdbaa48dd2
Create Date: 2022-09-15 02:46:35.363586

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '23912124a644'
down_revision = '5fcdbaa48dd2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('time', sa.Integer(), nullable=True))
    op.drop_column('posts', 'duration')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('duration', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('posts', 'time')
    # ### end Alembic commands ###
