"""datetime

Revision ID: 34f27ccb3f58
Revises: 485262e6542c
Create Date: 2022-09-13 07:24:05.182678

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34f27ccb3f58'
down_revision = '485262e6542c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
