"""init

Revision ID: 486d38389298
Revises: 
Create Date: 2022-09-14 02:58:32.525864

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '486d38389298'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_favorite_posts',
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('post_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.post_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_favorite_posts')
    # ### end Alembic commands ###
