"""create Follow table

Revision ID: 57810e5044e9
Revises: 65e37beadee4
Create Date: 2022-09-13 02:17:23.874408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57810e5044e9'
down_revision = '65e37beadee4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('follow',
    sa.Column('follower_id', sa.Integer(), nullable=False),
    sa.Column('followee_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('follower_id')
    )
    op.add_column('posts', sa.Column('duration', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('hashed_passowrd', sa.String(length=512), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'hashed_passowrd')
    op.drop_column('posts', 'duration')
    op.drop_table('follow')
    # ### end Alembic commands ###
