"""Added columns.



Revision ID: 5fcdbaa48dd2
Revises: 32099df8c285
Create Date: 2022-09-14 12:56:52.585380

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5fcdbaa48dd2'
down_revision = '32099df8c285'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('provisional_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=False),
    sa.Column('hashed_password', sa.String(length=128), nullable=False),
    sa.Column('token', sa.String(length=256), nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('expired_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_index(op.f('ix_provisional_users_email'), 'provisional_users', ['email'], unique=True)
    op.create_index(op.f('ix_provisional_users_id'), 'provisional_users', ['id'], unique=False)
    op.create_index(op.f('ix_provisional_users_name'), 'provisional_users', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_provisional_users_name'), table_name='provisional_users')
    op.drop_index(op.f('ix_provisional_users_id'), table_name='provisional_users')
    op.drop_index(op.f('ix_provisional_users_email'), table_name='provisional_users')
    op.drop_table('provisional_users')
    # ### end Alembic commands ###
