"""add follow

Revision ID: 720fa249dfe1
Revises: 57810e5044e9
Create Date: 2022-09-13 04:55:10.695214

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '720fa249dfe1'
down_revision = '57810e5044e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('follow', 'followee_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.add_column('users', sa.Column('email', sa.String(length=32), nullable=False))
    op.add_column('users', sa.Column('hashed_password', sa.String(length=512), nullable=False))
    op.drop_column('users', 'hashed_passowrd')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hashed_passowrd', mysql.VARCHAR(length=512), nullable=False))
    op.drop_column('users', 'hashed_password')
    op.drop_column('users', 'email')
    op.alter_column('follow', 'followee_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
