"""rm relationship

Revision ID: 8c6b130e481f
Revises: 720fa249dfe1
Create Date: 2022-09-13 05:02:54.289686

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c6b130e481f'
down_revision = '720fa249dfe1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
