"""datetime

Revision ID: ab33eaff578d
Revises: 34f27ccb3f58
Create Date: 2022-09-13 07:30:29.594042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab33eaff578d'
down_revision = '34f27ccb3f58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
